### ISSUE TITLE
Force Logging if value equal does not respect logging interval

### ISSUE THREAD

**Issue by kleenxcoder** [ioBroker/ioBroker.sql#149]
**Force Logging if value equal does not respect logging interval**  
For example if you set logging to one an hour (3600000 ms) and you set "force logging if previous value equal" to 1 (which means aktiv), then hourly logging is ignored. In this case the table is filled up continsously.

**To Reproduce**  
![ioBrokerSQLLoggingIssue](https://user-images.githubusercontent.com/26869780/108626670-ae471880-7451-11eb-8b49-11c9d56af4e5.PNG)

**Expected behavior**  

**Screenshots & Logfiles**  
![ioBrokerSQLLoggingIssue](https://user-images.githubusercontent.com/26869780/108626670-ae471880-7451-11eb-8b49-11c9d56af4e5.PNG)

**Versions:**  
 - Adapter version: 1.15.5
 - JS-Controller version: 3.1.6
 - Node version: v14.15.4
 - Operating system: Linux iobroker 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux

**Comment by Apollon77** [comment]
I think duplicate #53 ...

**Comment by kleenxcoder** [comment]
@Apollon77 -> jup looks like  a duplicate of #53 
Btw.; 
- Issue's #53 description should be modified. A link to the discussion forum is something I would immediately close or reject.
- I don't understand why issue #53 has not been fixed since 2018

**Comment by Apollon77** [comment]
1.) We accept also forum links ... better such a issue report then nothing ;-)
2.) because only a handful of people reported this as a topic (count the thinbs up if you like ;) ) in many thousand installations of 3 comparable statistic adapters ... and also noone from community stepped in and provided a PR for this. So it needs to wait until someone finds time. Additionally the underlaying reason is a "feature", so it is not that easy to find the correct way to handle it without breaking the feature.

We discussed that ipic 2 weeks ago and decided on how toproceed - now it is "Just" time that's needed.

And BTW one comment to your initial post:

>  if you set logging to one an hour (3600000 ms) 

But setting the "debouce time" (Entpreellzeit) it means normally: ONLY log a value when it was UNCHANGED for the given amount oof time! So if your value changes every 10 minutes and never stays the same and you will not get one single value logged!!
