### ISSUE TITLE
After update to 2.1.7 error too many connections. 

### ISSUE THREAD

**Issue by Kopierwichtel** [ioBroker/ioBroker.sql#262]
**Describe the bug**  
Today i updated the adapter to version 2.1.7. After this update I get lots of errors "error: tut mir leid, schon zu viele Verbindungen" / too many connections. 
I'm not sure if really the connection limit is reached or if the message is wrong, because data is written to the DB., Grafana diagrams are updated, but maybe not for all datapoints

**To Reproduce**  
I updated to version 2.1.7.

**Expected behavior**  
No error is popping

**Screenshots & Logfiles**  
The log is attached with debug on (at least at the end)
I removed everything before adding the two devices.
The update to 2.1.7 started at line  2191.
The error message only appeared after the update

[sql log2.txt](https://github.com/ioBroker/ioBroker.sql/files/9173427/sql.log2.txt)

**Versions:**  
 - Adapter version: @1.16.2 to @2.1.7
 - JS-Controller version: 4.0.23
 - Node version: V14.19.0
 - Operating system: docker buanet 

**Additional context**  
I changed the connection limit to 1000 in the adapter settings but this did not change the behaviour.
Then i changed it in postgresql server (to 200), but did not work aswell. I'm not sure but i think that after the last change it took longer before receiving this error. For me it looks like that the connections are not closed properly.

**Comment by Kopierwichtel** [comment]
What i noticed is, that the max_active value of the SQL adapter is set to 101 instead of 100. This only happened after the update aswell

Before:
`Zeile 1234: 2022-07-22 22:10:21.615  - [32minfo[39m: sql.1 (5459) Postgres connection options: {"server":"192.168.0.4","host":"192.168.0.4","user":"postgres","password":"****","max_idle":2,"max_active":100,"max_wait":10000,"when_exhausted":"block","port":5432,"database":"postgres"}`

After:
`2022-07-22 22:27:16.394  - [32minfo[39m: sql.1 (6870) Postgres connection options: {"server":"192.168.0.4","host":"192.168.0.4","user":"postgres","password":"****","max_idle":2,"max_active":101,"max_wait":10000,"when_exhausted":"block","port":5432,"database":"postgres"}`

**Comment by Apollon77** [comment]
Interesting. We did big efforts to make sure that the broken connection limiting in earlier versions ifs fixed now.
because of this the connection limits are now haneld by the adapter anD  NOT by the library ... thats why we tell the library that "Limit+1" is ok because the limiting from them is no longer used at all. So this is a trick to disable it.

Please enable debug log for the instance. Then you can see the status of the internal connection pool. Please provide a log here.

**Comment by Kopierwichtel** [comment]
@Apollon77  the log in my original post has already the debug enabled

**Comment by Apollon77** [comment]
hm ... the config fropm the latest start is 

2022-07-22 23:44:05.375  - [32minfo[39m: sql.1 (12444) Postgres connection options: {"server":"192.168.0.4","host":"192.168.0.4","user":"postgres","password":"****","max_idle":2,"max_active":1001,"max_wait":10000,"when_exhausted":"block","port":5432,"database":"postgres"}

... 1000 connections??? really? ;-) ANd yes then he will use >100 :-)

please show a debug log with 100 as setting to see if he use more then 100

**Comment by Kopierwichtel** [comment]
Size does matter ;-) 1000 was just my idea to check if its then solved. I reduced it to 200 already (most likely after sending the yesterdays log. 

Do i understand it right that its the Borrow from pool logentry which is somehow relevant?

Pfa a log with connection set to 100

[sql conn 100.log](https://github.com/ioBroker/ioBroker.sql/files/9173671/sql.conn.100.log)

10 mins after the adapter restart the error is not happening until now

**Comment by Apollon77** [comment]
In the logs you can see the pool  ...

> Borrow connection from pool: 85 now

means that a new connection was got from the pool because in limit

Normally this should go down to 0 again, else there would be an issue. In your case it really seems that a lot of data are puhed to the db -  you maybe should think about enabling the new "data buffer" mode so that per datapoint not each single value is written to the DB but e.g. after 10 or such".

But in fact te pool is as it should be ... goes up and down again ... not to 0, but this is because of your load of trx ... hm por the DB is answering strang ... as you can see the value is increasing and increasing and then "in bulk" it gets freed a lot ... e.g, 2022-07-23 13:41:24 it free'd 50 trx at once

And 2022-07-23 13:41:40 you can also see how the adapter behaves when it reaches the 100 connections ...

In fact my result for now:
1.) Connectoion pool works as expected
2.) The number of data cahnes that come in "in parallel" 100 connections might be too low and you should increase it
3.) You could limit the number of written data by using the buffers introduced as jew feature in 2. of the adapter to not send every single recond to the DB
4.) Check the load on the DB host if the DB can handle that many data in oarallel (in the end speaks mroe for the buffering)
