### ISSUE TITLE
Multiple data storage with same value

### ISSUE THREAD

**Issue by Seqway** [ioBroker/ioBroker.sql#66]
Dear all,
i tested now a lot of things but it seems to be that the sql adapter stores the same value even if i click on main menu "store only changes". 
Also individually in the datapoints no configuration delivers same value only once written.
Can you please tell me which configuration i must take ?

1.289 | true | tankerkoenig.0 | 2019-02-24 13:00:50.893 |  
1.289 | true | tankerkoenig.0 | 2019-02-24 12:00:50.860 |  
1.229 | true | tankerkoenig.0 | 2019-02-24 11:54:50.796 |  
1.229 | true | tankerkoenig.0 | 2019-02-24 10:00:50.824 |  
1.279 | true | tankerkoenig.0 | 2019-02-24 09:54:50.870 |  
1.279 | true | tankerkoenig.0 | 2019-02-24 09:27:50.782 |  
1.309 | true | tankerkoenig.0 | 2019-02-24 09:18:50.847 |  
1.309 | true | tankerkoenig.0 | 2019-02-24 08:18:50.822 |  
1.339 | true | tankerkoenig.0 | 2019-02-24 08:09:50.833 |  
1.369 | true | tankerkoenig.0 | 2019-02-24 08:00:50.894 |  
1.369 | true | tankerkoenig.0 | 2019-02-24 06:00:50.858

see also attached file
<img width="718" alt="bildschirmfoto 2019-02-24 um 14 38 44" src="https://user-images.githubusercontent.com/40624961/53299989-f40c7e80-3841-11e9-9498-37270673fb41.png">
<img width="1430" alt="bildschirmfoto 2019-02-24 um 14 38 16" src="https://user-images.githubusercontent.com/40624961/53299990-f4a51500-3841-11e9-8d50-c0ee302287f4.png">

**Comment by Apollon77** [comment]
Yes this is intended behaviour. Using "log changes only" the system internally remembers the last value that was skipped and logs that one on value change additionally. This is done to show how long the old value really was the current one, so that charts shows the correct values and also the values can be used to calculate stuff like integrals or such.
So 100% intended
