### ISSUE TITLE
Add manual triggern object

### ISSUE THREAD

**Issue by Fatmax1982** [ioBroker/ioBroker.sql#79]
Please add manual trigger object for every monitored object so that manual data transfer to SQL DB can be initiated by script.

**Comment by Apollon77** [comment]
Hi,  
Interesting idea. 
Why you need it? What is your usecase?

I would more think about adding a way to log values by javascript calls?!

**Comment by Fatmax1982** [comment]
In my case i would need it to catch temperature values always at a fixed time.
At the moment there is only time intervall available which i think it starts new when adapter is restarted.
With the additional trigger object you have the choice to start the value upload by cron or any other event at the script.

**Comment by Apollon77** [comment]
The easy workaround is to create custom states and fill them using a javascript script running at tzhose exact times and history them instead of the original ones ...

**Comment by Fatmax1982** [comment]
We know the workaround but that's not the best way and you also have the double objects with values and a more complicated script.

**Comment by Apollon77** [comment]
My thinking topic at the moment is that the adapter relies on real state information at the moment. With this change we would log fake values because you do not really want „the current value of the state when you trigger“ but you want the value only with a faked timestamp of „now“ or a given one. And we also have the other meta data of the State like lc and q and ack. What should they set to?

So generic would be a „storeValue“ JavaScript message to accept a fully defined state object to be logged. And when I remember this already exists. In fact this is nearly the same as the fake states. It may feel overhead but with the flexible structure of iobroker they are not.

What’s your opinion to the above?
